name: inburgering_trainer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  audioplayers: ^5.2.1
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  google_fonts: ^6.1.0
  http: ^1.2.0
  path: ^1.8.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  skeletonizer: ^1.0.1
  speech_to_text: ^6.6.0
  uuid: ^3.0.7
  flutter_sound: any
  record: ^5.0.4
  audio_waveforms: ^1.0.4
  mockito: ^5.4.4
  meta: ^1.10.0
  avatar_glow: ^3.0.1
  hydrated_bloc: ^9.1.4
  hive_flutter: ^1.1.0
  hive: 
  connectivity_plus: ^5.0.2
  intl: ^0.19.0
  fluttertoast: ^8.2.4
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 
  hive_generator:

flutter:
  uses-material-design: true


  assets:
    - assets/icons/
    - assets/
    - assets/images/

